site_name: Rocket
site_url: https://bloom.sh
repo_url: https://github.com/bloom42/rocket

theme:
  name: 'material'

nav:
  - index.md
  - aws_eb.md
  - aws_s3.md
  - custom_script.md
  - docker.md
  - github_releases.md
  - heroku.md
  - zeit_now.md
